name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_REGISTRY_USER }}
        password: ${{ secrets.GH_REGISTRY_TOKEN }}

    - name: Build and push Docker image to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        push: true
        repository: ${{ github.repository }}
        tags: ${{ github.repository }}:latest
