name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      id: checkout_code
      uses: actions/checkout@v2

    - name: Build and push Docker image to GitHub Packages
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}
        tags: latest
